### ISSUE TITLE
Fails on macOS due to different syntax for sed

### ISSUE THREAD

**Issue by chbndrhnns** [deliciousinsights/git-clean-stale-local#3]
When I run the script on macOS, it fails with:

```
sed: illegal option -- -
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
fatal: malformed object name
```

Could you maybe adopt it to macOS, as well?

**Comment by esaruoho** [comment]
would be intrigued to try this with macOS, too, for sure. any work being done on it?

**Comment by connorshea** [comment]
Me as well, unfortunately I'm not particularly familiar with sed.

**Comment by connorshea** [comment]
FWIW, it's possible to make it work on macOS by installing `gnu-sed` from homebrew, with `brew install gnu-sed` and then replacing `sed` commands in the script with `gsed`.

Alternatively, you can also replace the default installation of `sed` entirely with `gsed` so that `sed` commands use `gsed`.

**Comment by mbrehin** [comment]
Fixed. The `quiet` option is no more supported by sed. The `-n` is now used as it was already used later in the code.
